"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$fill\
$git_branch\
$git_status\
$git_metrics\
$time\
$cmd_duration\n  \
[ó°§±](fg:iris) \
"""

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
flamingo = "#f5c2e7"

[directory]
format = "[î‚¶](fg:overlay)[ $path ]($style)[î‚´](fg:overlay) "
style = "bg:overlay fg:rose"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
Documents = "ó°ˆ™"
Downloads = "ï€™ "
Music = "ï€ "
Pictures = "ï€¾ "

[localip]
ssh_only = false
format = '[î‚¶](fg:overlay)[ğ‹ƒ $localipv4]($style)[î‚´](fg:overlay)'
style = "bg:overlay fg:flamingo"
disabled = false

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[î‚¶](fg:overlay)[ $symbol $branch ]($style)[î‚´](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = "ï˜"

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[î‚¶](fg:overlay)([$all_status$ahead_behind]($style))[î‚´](fg:overlay) '
up_to_date = '[ âœ“ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:flamingo)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:flamingo)'
renamed = '[Â»\($count\)](bg:overlay fg:iris)'
deleted = '[âœ˜\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:flamingo)'
ahead = '[â‡¡\(${count}\)](bg:overlay fg:foam)'
diverged = 'â‡•[\[](bg:overlay fg:iris)[â‡¡\(${ahead_count}\)](bg:overlay fg:foam)[â‡£\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[â‡£\(${count}\)](bg:overlay fg:rose)'

[git_metrics]
format = '[î‚¶](fg:overlay)([îª¡ $added ]($added_style))([îªš $deleted]($deleted_style))[î‚´](fg:overlay) '
added_style = 'fg:flamingo bg:overlay'
deleted_style = 'fg:love bg:overlay'
ignore_submodules = true
disabled = false


[time]
disabled = false
format = " [î‚¶](fg:overlay)[ $time ó°´ˆ ]($style)[î‚´](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[î‚¶](fg:overlay)[ îœ $user ]($style)[î‚´](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:love"
style_user = "bg:overlay fg:love"

[cmd_duration]
show_milliseconds = true
format = " [î‚¶](fg:overlay)[ó±«ª in $duration ]($style)[î‚´](fg:overlay)"
style = "bg:overlay fg:love"
disabled = false
show_notifications = true
min_time_to_notify = 45000

# Languages

[c]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î˜ "

[elixir]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î‰µ "

[elm]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î˜¬ "

[golang]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "Ê•â Â·â á´¥â Â·â Ê”"

[haskell]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î· "

[java]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î™­ "

[julia]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î˜¤ "

[nodejs]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "ó°™ "

[nim]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "ó°†¥ "

[rust]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î¨ "

[scala]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "îœ· "

[python]
style = "bg:overlay fg:foam"
format = ' [î‚¶](fg:overlay)[ $symbol( $version)(\($virtualenv\)) ]($style)[î‚´](fg:overlay)'
disabled = false
symbol = 'îœ¼ '

[conda]
style = "bg:overlay fg:foam"
format = " [î‚¶](fg:overlay)[ $symbol$environment ]($style)[î‚´](fg:overlay)"
disabled = false
symbol = 'ğŸ…’ '